development:
  callback_url: 'http://0.0.0.0:3000/pesapal/callback'
  consumer_key: '<YOUR_DEV_CONSUMER_KEY>'
  consumer_secret: '<YOUR_DEV_CONSUMER_SECRET>'

production:
  callback_url: 'http://1.2.3.4:3000/pesapal/callback'
  consumer_key: '<YOUR_PROD_CONSUMER_KEY>'
  consumer_secret: '<YOUR_PROD_CONSUMER_SECRET>'
